joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular:
      yaw: 1.0

    
    enable_button: 6
    enable_turbo_button: 7

<<<<<<< HEAD
    require_enable_button: true
=======
    require_enable_button: true
>>>>>>> 09fe510840800cc742f057f706fb54c28a56e97b
